name: Publish

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.2
        with:
          path: ${{ github.event.repository.name }}
            
      - name: Checkout `worlds`
        uses: actions/checkout@v4.1.2
        with:
          repository: game-simulations/worlds
          token: ${{ secrets.PAT }}
          path: worlds
      
      - name: Checkout `types`
        uses: actions/checkout@v4.1.2
        with:
          repository: game-simulations/types
          token: ${{ secrets.PAT }}
          path: types
      
      - name: Checkout `unmanaged`
        uses: actions/checkout@v4.1.2
        with:
          repository: game-simulations/unmanaged
          token: ${{ secrets.PAT }}
          path: unmanaged
      
      - name: Checkout `bin-packer`
        uses: actions/checkout@v4.1.2
        with:
          repository: game-simulations/bin-packer
          token: ${{ secrets.PAT }}
          path: bin-packer
      
      - name: Checkout `collections`
        uses: actions/checkout@v4.1.2
        with:
          repository: game-simulations/collections
          token: ${{ secrets.PAT }}
          path: collections
            
      - name: Setup
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Set VERSION variable from tag
        run: echo "VERSION=${GITHUB_REF/refs\/tags\/v/}" >> $GITHUB_ENV
            
      - name: Build `Textures`
        run: dotnet build "${{ github.event.repository.name }}/source" -c Release /p:Version=${VERSION}
      
      - name: Build `Textures.Tests`
        run: dotnet build "${{ github.event.repository.name }}/tests" -c Release /p:Version=${VERSION}
            
      - name: Test
        run: dotnet test "${{ github.event.repository.name }}/tests" -c Release --logger "trx"
            
      - name: Pack `Textures`
        run: dotnet pack "${{ github.event.repository.name }}/source" -c Release /p:Version=${VERSION} --no-build --output .

      - name: Add NuGet Source
        run: dotnet nuget add source https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json --name github --username ${{ github.repository_owner }} --password ${{ github.token }} --store-password-in-clear-text
            
      - name: Publish `Textures`
        run: dotnet nuget push Textures.${VERSION}.nupkg --source github --api-key ${NUGET_TOKEN}
        env:
          NUGET_TOKEN: ${{ secrets.NUGET_TOKEN }}